### ISSUE TITLE
Síntesis

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-JoseABCruz#1]

**Comment by JoseABCruz** [comment]
[Síntesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-JoseABCruz/files/12704298/Sintesis.pdf)

**Comment by Gregorio012** [comment]
Calf: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
